# Generated by Django 5.0.1 on 2024-06-08 13:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('\\+\\d{9-15}$', message='Phone number format should be +111222333444')])),
                ('subscription', models.CharField(choices=[('single', 'S'), ('family', 'F')], max_length=6)),
                ('payment', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=7)),
                ('price', models.PositiveIntegerField()),
                ('insurance_status', models.CharField(choices=[('active', 'A'), ('inactive', 'I')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('relation', models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter')], max_length=8)),
                ('age', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'A'), ('inactive', 'I')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.medicalinsurance')),
            ],
        ),
        migrations.AddIndex(
            model_name='medicalinsurance',
            index=models.Index(fields=['customer'], name='core_medica_custome_2ade8b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalinsurance',
            index=models.Index(fields=['subscription'], name='core_medica_subscri_5b1b03_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalinsurance',
            index=models.Index(fields=['insurance_status'], name='core_medica_insuran_8abe50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicalinsurance',
            unique_together={('customer', 'subscription')},
        ),
        migrations.AddIndex(
            model_name='familyinsurance',
            index=models.Index(fields=['first_name', 'last_name', 'age'], name='core_family_first_n_57ab22_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinsurance',
            index=models.Index(fields=['insurance'], name='core_family_insuran_7666a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyinsurance',
            unique_together={('first_name', 'insurance', 'relation')},
        ),
    ]
