# Generated by Django 5.0.1 on 2024-06-08 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalinsurance_number_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinsurance',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('\\+?\\d{9,15}$', message='Phone number format should be +111222333444')]),
        ),
    ]
