# Generated by Django 5.0.1 on 2024-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_medicalinsurance_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinsurance',
            name='number_of_members',
        ),
        migrations.AddField(
            model_name='medicalinsurance',
            name='family_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalinsurance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
