# Generated by Django 5.0.1 on 2024-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_medicalinsurance_number_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinsurance',
            name='insurance_status',
            field=models.CharField(choices=[('active', 'A'), ('inactive', 'I'), ('cancelled', 'C')], default='active', max_length=9),
        ),
    ]
