# Generated by Django 5.0.1 on 2024-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicalinsurance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinsurance',
            name='insurance_status',
            field=models.CharField(choices=[('active', 'A'), ('inactive', 'I'), ('cancelled', 'C')], default='inactive', max_length=9),
        ),
    ]
